-------------------------------- Datos Iniciales--------------------------------
INSERT INTO clientes (nombre, cuit, actividad) VALUES
('YPF SA', '30-54668997-9', 'OPERADORA GAS Y PETROLEO'),
('TRANSPORTADORA DE GAS DEL SUR SA', '30-65786206-8', 'OPERADORA DE DUCTOS'),
('TECPETROL SA', '30-59266547-2', 'OPERADORA GAS Y PETROLEO'),
('YAC LINDERO ATRAVESADO', '30-63679858-0', 'OPERADORA GAS Y PETROLEO'),
('PAMPA ENERGIA SA CHIUIDOS', '30-63714786-9', 'OPERADORA GAS Y PETROLEO'),
('UTE LOS TOLDOS (TECPETROL)', '30-71217040-5', 'OPERADORA GAS Y PETROLEO');

INSERT INTO disciplinas (tipo, descripcion) VALUES
('A', 'Arquitectura'),
('P', 'Cañerías'),
('C', 'Civil'),
('E', 'Electricidad'),
('S', 'Estructuras Metálicas'),
('I', 'Instrumentación'),
('M', 'Mecánica'),
('R', 'Procesos'),
('T', 'Topografía'),
('G', 'Generales'),
('Y', 'Medioambiente y Seguridad');

INSERT INTO tipo_documento (tipo, descripcion) VALUES
('BD', 'Bases de diseño'),
('DF', 'Diagrama de flujo'),
('DL', 'Diagrama de lazo'),
('DU', 'Diagrama unifilar'),
('ET', 'Especificación técnica'),
('FO', 'Filosofía de operación y control'),
('HD', 'Hoja de datos'),
('HZ', 'Hazop'),
('IS', 'Isométricos'),
('LC', 'Lista de cables'),
('LD', 'Lista de documentos'),
('LE', 'Lista de equipos'),
('LI', 'Lista de instrumentos'),
('LL', 'Lista de líneas'),
('LP', 'Lista de planos'),
('LS', 'Lista de isométricos'),
('LV', 'Lista de válvulas'),
('LY', 'Layout'),
('MC', 'Memoria de cálculo'),
('MD', 'Memoria descriptiva'),
('MM', 'Manual de mantenimiento'),
('MO', 'Manual operativo'),
('OT', 'Otros'),
('PB', 'Planilla de bornes'),
('PH', 'Planilla de hierros'),
('PI', 'P&ID'),
('PL', 'Planos'),
('PM', 'Planilla de materiales'),
('PT', 'Planialtimetría'),
('RI', 'Requisición de Ingeniería'),
('ST', 'Normas'),
('TI', 'Típico'),
('AQ', 'Arquitectura sistemas de control-telesupervisión-fire&gas'),
('BM', 'Balance de masa y energía'),
('CA', 'Clasificiación de áreas peligrosas'),
('CD', 'Notificación de cambio'),
('CE', 'Matriz causa-efecto'),
('CI', 'Cronograma de ingeniería'),
('CL', 'Lista de verificación'),
('DC', 'Diagrama de cableado interior tableros/equipos'),
('DN', 'Diagrama funcional'),
('GP', 'Programa Gantt'),
('IF', 'Informe técnico'),
('LM', 'Lista de materiales'),
('LR', 'Lista de cargas eléctricas'),
('LU', 'Lista de respuestos para puesta en marcha'),
('LA', 'Lista de señales'),
('LT', 'Listado de Tie ins'),
('MT', 'Memoria Técnica'),
('PC', 'Planilla de conexionado en tableros y equipos'),
('PE', 'Protocolo de ensayo'),
('PG', 'Pliego de condiciones'),
('PS', 'Planilla de seguimiento de emisión y recepción de documentos'),
('QV', 'Documento de calidad'),
('SP', 'Planos de soportes escaleras y plataformas'),
('WP', 'Porcedimiento de soldadura');

INSERT INTO roles (nombre_rol, descripcion) VALUES 
('Administrador', 'Acceso total al sistema, gestión de clientes y proyectos.'),
('Coordinador', 'Gestión de documentos, emisiones, remitos y visualización de KPIs.'),
('Proyectista', 'Carga de horas personales y visualización de documentos asignados.');

INSERT INTO reglas_de_avance (tipo_revision, porc_fisico, porc_certificacion) VALUES 
('Revisión A', 70, 50),
('Revisión B', 85, 75),
('Revisión 0', 100, 100);
